# Generated by Django 4.2.4 on 2023-08-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='variklis',
            field=models.CharField(max_length=100, verbose_name='Variklis'),
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=15, verbose_name='Valstybinis numeris')),
                ('vin', models.CharField(max_length=21, verbose_name='VIN numeris')),
                ('klientas', models.CharField(max_length=100, verbose_name='Klientas')),
                ('automobiliomodelis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automobiliomodelis')),
            ],
            options={
                'ordering': ['klientas'],
            },
        ),
    ]
