# Generated by Django 4.2.4 on 2023-08-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_automobiliomodelis_variklis_automobilis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Uzsakymo data')),
                ('suma', models.FloatField(verbose_name='Uzsakymo suma')),
                ('automobilis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automobilis')),
            ],
        ),
    ]
