# Generated by Django 4.2.4 on 2023-08-22 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_uzsakymas'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Priimta'), ('t', 'Tvarkoma'), ('g', 'Galima paimti')], default='p', help_text='Tvarkymo statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
