# Generated by Django 4.2.4 on 2023-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_uzsakymas_status_alter_uzsakymas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paslaugos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Paslaugos pavadinimas')),
                ('kaina', models.FloatField(verbose_name='Paslaugos kaina')),
            ],
        ),
    ]
