# Generated by Django 4.2.4 on 2023-08-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0005_paslaugos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzsakymoeilutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(help_text='Kiek kartų užsakyta', verbose_name='Uzsakymu kiekis')),
                ('kaina', models.FloatField(verbose_name='Uzsakymo kaina')),
                ('paslaugos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.paslaugos')),
                ('uzsakymas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.uzsakymas')),
            ],
        ),
    ]
