# Generated by Django 4.2.4 on 2023-08-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_uzsakymoeilutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobiliomodelis',
            options={'ordering': ['marke'], 'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobilių modeliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'ordering': ['klientas'], 'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='paslaugos',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilutes',
            options={'verbose_name': 'Visi užsakymai', 'verbose_name_plural': 'Užsakymų eilutės'},
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='automobiliomodelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto', to='autoservisas.automobiliomodelis'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(verbose_name='Užsakymo data'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Priimta'), ('t', 'Tvarkoma'), ('g', 'Galima paimti')], default='p', help_text='Tvarkymo statusas', max_length=1, verbose_name='Statusas'),
        ),
    ]
