# Generated by Django 4.2.4 on 2023-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_alter_automobiliomodelis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Foto'),
        ),
    ]
